version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: find .
      - run: dotnet restore S3ImageProcessing/S3ImageProcessing.sln
      - run: dotnet build S3ImageProcessing/S3ImageProcessing/S3ImageProcessing.csproj
      - run: dotnet test --no-build S3ImageProcessing/S3ImageProcessing.Tests/S3ImageProcessing.Tests.csproj
